# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e146526f9b1d9ce1d29bbdbf7e5e0a50d677668addc9b8de8f7e0e94763d0ff76c303ee40014c6a24ab5f1bbdf53167a0e4c7dadba0348775f6874b37a6dd35

test:
  secret_key_base: 82803ff32a6b92b280ffbe7a135bc8cfef207a90733d86f484ba1659308e324b97e3019eba5d23e6175f7eb56ce48fdff3e6420525638df2d3ad181164b224ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
